### ISSUE TITLE
Please guide aboud badge's 

### ISSUE THREAD

**Issue by Drago09t** [Astra-Development/Discord-Bot-List-v3#19]
how user can give promoted badge to a bot or server

**Comment by johnandreopoulos** [comment]
Certainly! A new feature has been added that enables users to manually promote bots. You can now utilize specific Discord commands to promote a bot. For detailed instructions and to stay informed about the latest changes, please refer to the following GitHub commit: [Link to the commit](https://github.com/Astra-Development/Discord-Bot-List-v3/commit/f8c7c8d40edc78cdf6a0663e80809cf3640e30a1)
