### ISSUE TITLE
I can't add more than 1 server and I can't add any bots

### ISSUE THREAD

**Issue by dioverdm** [Astra-Development/Discord-Bot-List-v3#22]
The website does not allow me to add more than 1 server and I cannot add any bot and I have tried a thousand ways but it won't let me.

Also when I try to add a bot it tells me that the webhook is invalid and I change the webhook and it keeps saying the same thing.

With the server it only tells me that there is an error and it has already been communicated to the administrators

**Comment by johnandreopoulos** [comment]
This segment of the code exclusively permits webhook URLs that commence with 'https://discord.com/api'. You can find the specific code here: https://github.com/Astra-Development/Discord-Bot-List-v3/blob/3bdbb5895af0e1708136f1e7869acea06d15e352/routes/bots/add.js#L120-L136

# Code explanation
1. **Check if webhookURL exists**: It starts by checking if `webhookURL` exists. If it does, it proceeds with further validation. If not, it probably returns an error.
2. **Check if webhookURL is a string and has the correct format**: It checks if `webhookURL` is a string and if it contains the base URL for Discord webhooks (`https://discord.com/api/`). If `webhookURL` is not a string or doesn't contain the correct base URL, it returns an error.
3. **Parsing segments of the URL**: It splits the URL into segments using "/" as a delimiter and extracts certain parts of it.
4. **Adjusting version**: It checks the version of the webhook URL. If it's using an older version (`v6`, `v7`, `v8`, or `v9`), it converts it to `v10`. If it doesn't start with `v10`, it returns an error.
5. **Further validation**: It performs additional checks on the segments extracted from the URL. It ensures that the URL follows a specific pattern and contains the required segments. If any of the checks fail, it returns an error.
6. **Testing the webhook URL**: It tries to fetch the URL using `fetch` and checks if the response is successful (`resp.ok`). If the response is not OK, it returns an error.
7. **Error handling**: If any errors occur during the process (such as network errors during the fetch operation), it catches the error and returns an error response.
Overall, this code snippet ensures that the provided Discord webhook URL is valid and conforms to a specific format expected by the application. If the URL is not valid, it returns an error message indicating that the webhook URL is not valid.


# To generate a webhook, refer to the documentation outlined in the following steps provided by Discord's official documentation:

<section class="article-info">
   <div class="article-content">
      <div class="article-body">
         <h1>Making a Webhook</h1>
         <p>With that in mind, if you want to&nbsp;update your Discord server with&nbsp;<strong>GitHub commits and pull requests</strong> or&nbsp;<strong>track analytics from DataDog</strong> or anything similar, here's how!</p>
         <ol>
            <li>Open your <strong>Server Settings</strong> and head into the <strong>Integrations</strong> tab:</li>
            <li>Click the "<strong>Create Webhook</strong>" button to create a new webhook!</li>
         </ol>
         <p class="wysiwyg-text-align-center"><img src="https://support.discord.com/hc/article_attachments/1500000463501" alt="Screen_Shot_2020-12-15_at_4.41.53_PM.png"></p>
         <p>You'll have a few options here. You can:</p>
         <ul>
            <li>&nbsp;<strong>Edit the avatar:&nbsp;</strong>By clicking the avatar next to the Name in the top left</li>
            <li><strong>Choose what channel the Webhook posts to:</strong>&nbsp;By selecting the desired text channel in the &nbsp;dropdown menu.</li>
            <li><strong>Name your Webhook: </strong>Good for distinguishing multiple webhooks for multiple different services.</li>
         </ul>
         <p>You now have your own&nbsp;handy URL / pneumatic tube <em>schoomp</em>-er&nbsp;that you can link to more websites to receive messages from.&nbsp;</p>
         <p class="wysiwyg-text-align-center"><img src="https://support.discord.com/hc/article_attachments/360101553853" alt="Screen_Shot_2020-12-15_at_4.51.38_PM.png" width="650" height="393"></p>
         <h1>Quick Example: GitHub Webhook Integration</h1>
         <p>Since webhooks can't really function on their own and need to be linked to another website to function as intended, I figured it'd be best to include a sample integration for any of you GitHub enthusiasts and code-pushers.</p>
         <p>You can use Discord's webhooks to send any code merge or push updates in a repository of yours into a text channel in your server.&nbsp;&nbsp;</p>
         <p><strong><span class="wysiwyg-font-size-large">1. Get the webhook URL for the server/channel you want to receive messages:</span></strong></p>
         <p>In my server, I've created a text channel labeled #general-chat and I want my repo updates to post messages here!</p>
         <p>Therefore, I'll grab the webhook URL for this channel by pressing the <strong>Copy Webhook URL</strong> button:</p>
         <p class="wysiwyg-text-align-center"><img src="https://support.discord.com/hc/article_attachments/1500000455142" alt="Screen_Shot_2020-12-15_at_4.45.52_PM.png" width="601" height="609"></p>
      </div>
      <div class="article-attachments">
         <ul class="attachments">
         </ul>
      </div>
   </div>
</section>
