### ISSUE TITLE
IDs not in config

### ISSUE THREAD

**Issue by DairyWeb3638077** [Astra-Development/Discord-Bot-List-v3#6]
Please find all ids in the code and put them in the config file. some features do not work if ids are wrong.

**Comment by johnandreopoulos** [comment]
I cannot locate your IDs, so everything should be completed based on your bots and server channel ids and roles.

**Comment by DairyWeb3638077** [comment]
> I cannot locate your IDs, so everything should be completed based on your bots and server channel ids and roles.

now my IDs, any ids that are stranded in the code.

**Comment by johnandreopoulos** [comment]
I believe the code is clear, and the ids and other information are stored in the config file. The only check within the page is in the `header.ejs` **line 68**, which I changed and committed.
